-- Warranty Tracker database schema (PostgreSQL 15+).
-- IDs are generated by the application so this schema does not depend on a
-- PostgreSQL UUID extension. Store all instants in UTC.

CREATE TABLE public.app_user (
    id UUID PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(320) NOT NULL,
    -- Null for users who authenticate only through an external identity.
    password_hash VARCHAR(255),
    email_verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_app_user_email UNIQUE (email)
);

-- A user may sign in with a local password and/or an OAuth provider.
CREATE TABLE public.user_identity (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.app_user(id) ON DELETE CASCADE,
    provider VARCHAR(30) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    provider_email VARCHAR(320),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_user_identity_provider_subject UNIQUE (provider, provider_subject),
    CONSTRAINT uq_user_identity_provider_user UNIQUE (provider, user_id),
    CONSTRAINT ck_user_identity_provider CHECK (provider IN ('GOOGLE'))
);

-- Created only after a user explicitly connects Gmail for invoice import.
-- The refresh token must be encrypted by Spring Boot before insertion.
CREATE TABLE public.gmail_connection (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.app_user(id) ON DELETE CASCADE,
    gmail_address VARCHAR(320) NOT NULL,
    encrypted_refresh_token BYTEA NOT NULL,
    encryption_key_version VARCHAR(50) NOT NULL,
    granted_scopes TEXT NOT NULL,
    connected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_gmail_connection_user_address UNIQUE (user_id, gmail_address)
);

CREATE TABLE public.warranty (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.app_user(id) ON DELETE CASCADE,

    -- Product identification
    product_name VARCHAR(200) NOT NULL,
    brand VARCHAR(100),
    model_number VARCHAR(100),
    serial_number VARCHAR(150),
    category VARCHAR(80),

    -- Purchase information
    purchase_date DATE NOT NULL,
    purchase_price NUMERIC(12, 2),
    currency CHAR(3),
    retailer_name VARCHAR(160),
    retailer_order_number VARCHAR(150),

    -- Warranty coverage
    warranty_provider VARCHAR(160),
    warranty_type VARCHAR(30) NOT NULL DEFAULT 'MANUFACTURER',
    policy_number VARCHAR(150),
    coverage_start_date DATE,
    expiry_date DATE NOT NULL,
    coverage_terms TEXT,
    support_phone VARCHAR(50),
    support_email VARCHAR(320),
    support_url VARCHAR(2048),

    -- User-maintained state
    notes TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT ck_warranty_dates CHECK (expiry_date >= purchase_date),
    CONSTRAINT ck_warranty_coverage_dates CHECK (
        coverage_start_date IS NULL OR coverage_start_date >= purchase_date
    ),
    CONSTRAINT ck_warranty_price CHECK (purchase_price IS NULL OR purchase_price >= 0),
    CONSTRAINT ck_warranty_currency CHECK (currency IS NULL OR currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_warranty_type CHECK (
        warranty_type IN ('MANUFACTURER', 'EXTENDED', 'SELLER', 'INSURANCE', 'OTHER')
    ),
    CONSTRAINT ck_warranty_status CHECK (
        status IN ('ACTIVE', 'CLAIMED', 'EXPIRED', 'ARCHIVED')
    )
);

CREATE TABLE public.warranty_attachment (
    id UUID PRIMARY KEY,
    warranty_id UUID NOT NULL REFERENCES public.warranty(id) ON DELETE CASCADE,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(150) NOT NULL,
    size_bytes BIGINT NOT NULL,
    -- Private Supabase Storage object path, never a public URL.
    -- Format: {userId}/{warrantyId}/{uuid}.{extension}
    storage_key VARCHAR(512) NOT NULL,
    attachment_type VARCHAR(30) NOT NULL DEFAULT 'RECEIPT',
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_warranty_attachment_storage_key UNIQUE (storage_key),
    CONSTRAINT ck_attachment_size CHECK (size_bytes > 0),
    CONSTRAINT ck_attachment_type CHECK (
        attachment_type IN ('RECEIPT', 'WARRANTY_CARD', 'MANUAL', 'PHOTO', 'OTHER')
    )
);

CREATE TABLE public.warranty_reminder (
    id UUID PRIMARY KEY,
    warranty_id UUID NOT NULL REFERENCES public.warranty(id) ON DELETE CASCADE,
    reminder_date DATE NOT NULL,
    channel VARCHAR(20) NOT NULL DEFAULT 'IN_APP',
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_warranty_reminder UNIQUE (warranty_id, reminder_date, channel),
    CONSTRAINT ck_reminder_channel CHECK (channel IN ('IN_APP', 'EMAIL'))
);

CREATE INDEX ix_warranty_user_expiry ON public.warranty (user_id, expiry_date);
CREATE INDEX ix_warranty_user_status ON public.warranty (user_id, status);
CREATE INDEX ix_gmail_connection_active ON public.gmail_connection (user_id) WHERE revoked_at IS NULL;
CREATE INDEX ix_attachment_warranty ON public.warranty_attachment (warranty_id);
CREATE INDEX ix_reminder_due ON public.warranty_reminder (reminder_date) WHERE sent_at IS NULL;
